development:
  adapter: mysql2
  database: squarrels
  username: root
  password:
  host: 127.0.0.1

test:
  adapter: mysql2
  database: squarrels_test
  username: root
  password:
  host: 127.0.0.1

